# Generated by Django 2.0.5 on 2019-04-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_field',
            new_name='email',
        ),
    ]
